#! /bin/sh

bspc monitor -d web chat term syst media

killall -9 sxhkd polybar dunst compton nm-applet nitrogen

sxhkd &
$HOME/.local/bin/launch-polybar.sh &
xrdb $HOME/.Xresources &
nitrogen --restore &
compton --config "$HOME/.config/compton.conf" -b &
dunst &
numlockx &
pamac-tray &
nm-applet &
xsetroot -cursor_name left_ptr &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

bspc config border_width         3
bspc config window_gap          12
bspc config initial_polarity        second_child

bspc config split_ratio                            0.52
bspc config borderless_monocle         true
bspc config gapless_monocle               true
bspc config focus_follows_pointer       true

bspc config normal_border_color "#282a36"
bspc config focused_border_color "#d79921"
bspc config presel_feedback_color "#2c3939"



